# Base image
FROM golang:1.23-alpine AS builder

WORKDIR /app


COPY bot/go.mod bot/go.sum ./
RUN go mod download


COPY bot/*.go ./


RUN go build -o bot


FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/bot .
COPY .env .


CMD ["./bot"]
